apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: model-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: magnusdtd/app:latest     
        ports:
        - containerPort: 8000
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: SESSION_SECRET_KEY
          value: thisisasecretkey
        - name: IS_DOCKER_CONTAINER
          value: yes
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: model-serving
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: model-serving
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50