{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
  namespace: model-serving
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-role
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-ingress.serviceAccountName" . }}
  namespace: model-serving
{{- end }}
