replicaCount: 1

image:
  repository: magnusdtd/jenkins-practice-app
  pullPolicy: IfNotPresent
  tag: "latest"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "jenkins-practice.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "example-tls"
      hosts:
        - "jenkins-practice.com"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8000
readinessProbe:
  httpGet:
    path: /
    port: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  SESSION_SECRET_KEY: thisisasecretkey
  IS_DOCKER_CONTAINER: yes
